package com.differentdoors.hubspot.models.HubDB;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class TableForm {
    private String deal_id = "";
    private String title = "";
    private String adviseur = "";
    private String updated_at = "";
    private String definitieve_bestelmaat = "";
    private String dealname = "";
    private String actieve_deur = "";
    private String draairichting = "";
    private String kleuropties = "";
    private String krukset_deurbeslag = "";
    private String model = "";
    private String paneel = "";
    private String analoog_breedte = "";
    private String analoog_hoogte = "";
    private String digitaal_breedte = "";
    private String digitaal_hoogte = "";
    private String breedte = "";
    private String hoogte = "";
    private String verdeling_symmetrisch = "";
    private String cilinder = "";
    private String glassectie = "";
    private String montage = "";
    private String bestaande_deur = "";
    private String type_deur = "";
    private String vloeraanpassing = "";
    private String aftimmering_binnenzijde = "";
    private String bouwkundig_aanpassingen = "";
    private String indicatie_van_montage_uren = "";
    private String overige_opmerkingen_klant = "";
    private String overige_opmerkingen_intern = "";
    private String materiaal_te_bestellen_door_werkvoorbereiding = "";
    private String profilering = "";
    private String uitstraling = "";
    private String deur_in_een_kleur = "";
    private String deur_ral = "";
    private String kozijn_ral = "";
    private String scharnier_ral = "";
    private String netto_glasmaat = "";
    private String glassectie_in_vleugel = "";
    private String links = "";
    private String rechts = "";
    private Image fs1;
    private Image fs2;
    private Image fb1;
    private Image fb2;
    private Image fb3;
    private Image fg1;
    private String deur_reeds_ingemeten = "";
    private String maat_tussen_metselwerk = "";
    private String maat_tussen_latei = "";
    private String type_profilering = "";
    private String afstand_belijning = "";
    private String aflakken_op_locatie = "";
    private String uitstraling_binnenzijde = "";
    private String deur_ral_binnen = "";
    private String kozijn_ral_binnen = "";
    private String isolatie = "";
    private String omklapvoetjes = "";
    private String aantal_roedes = "";
    private String glasverdeling = "";
    private String uitvoerder_naam = "";
    private String uitvoerder_telefoon = "";
    private String uitvoerder_email = "";
    private String projectleider_naam = "";
    private String projectleider_telefoon = "";
    private String projectleider_email = "";
    private String type_sectionaaldeur = "";
    private String draairichting_zijwaartse = "";
    private String garagedeur = "";
    private String houtsoort = "";
    private String model_bekleding = "";
    private String behandeling = "";
    private String dekkend_ral = "";
    private String afgelakt = "";
    private String deurblad = "";
    private String deurblad_ral = "";
    private String rails = "";
    private String rails_ral = "";
    private String motor = "";
    private String stroom = "";
    private String positie = "";
    private String isolatie_in_de_deur = "";
    private String isoleren_van_gevel = "";
    private String buiten_bediening = "";
    private String aantal_handzenders = "";
    private String binnen_bediening = "";
    private String draadloze_drukknop = "";
    private String nooduitgang_aanwezig = "";
    private String nooduitgang_oplossing = "";
    private String aanbrengen_gevelbekleding = "";
    private String gevel_afmetingen = "";
    private String loopdeur_voordeur = "";
    private String kleur_kozijn = "";
    private String kleur_kozijn_ral = "";
    private String binnen_afwerking = "";
    private String vlakke_plaat_ral = "";
    private String deurgreep = "";
    private String loopdeur_voordeur_glassectie = "";
    private String indicatie_montage_uren = "";
    private String electrisch_motorslot = "";
    private String deur_afmetingen = "";
    private String montage_straat = "";
    private String montage_postcode = "";
    private String montage_plaats = "";
    private String transparant_kleurcode = "";
    private String gelijk_met_de_wand = "";
    private String aantal_draadloos_codeklavier = "";
    private String aantal_losse_ontvanger = "";
    private String type_glas = "";
    private String sluitkommen = "";
    private String type_dorpel = "";
    private String fase_project = "";
    private String verwachte_leverweek_klant = "";
    private String ventilatieroosters = "";
    private String deur_bestellen = "";
    private String stuiknaden = "";
    private String overige_opmerkingen_leverancier = "";
    private String begeleiding_project = "";
    private String verwachte_leverjaar_klant = "";
    private String status_project = "";
    private String type_woning = "";
    private String beide_personen_aanwezig_bij_gesprek_ = "";
    private String situatie = "";
    private String garage_aangrenzend_aan_woning = "";
    private String leeftijdsschatting = "";
    private String thuiswonende_kinderen = "";
    private String wie_is_er_bij_het_gesprek_aanwezig = "";
    private String geschatte_woningwaarde = "";
    private String wanneer_gaat_het_project_spelen_ = "";
    private String scharnierzijde = "";
}
